name: Backend CI

on:
  push:
    branches:
      - rasel
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r backend/requirements.txt
      - name: Print working directory
        run: pwd
      - name: Navigate to backend directory
        run: cd backend
      - name: Print working directory
        run: pwd
      - name: Check working directory
        run: |
          if [[ $(pwd) == *"backend"* ]]; then
            echo "Already in backend directory."
          else
            echo "Error: Not in backend directory. Please navigate to the backend directory before running tests."
        
      - name: Run tests
        run: python manage.py test
