name: Backend CI

on:
  push:
    branches:
      - rasel
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Print other directory
        run: cd backend && ls
      - name: Install dependencies
        run: pip install -r backend/requirements.txt
      - name: Print working directory
        run: pwd
      - name: Navigate to backend directory
        run: cd backend
      - name: Print working directory
        run: pwd
     
      - name: Run tests
        run: cd backend && python manage.py test && ls