name: Frontend CI

on:
  push:
    branches:
      - rasel
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js (16.x LTS recommended)
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Update to the desired version

      - name: Install dependencies
        working-directory: frontend
        run: |
          npm install --force


